spring:
  application:
    name: genshin-artifact-manager
  profiles:
    active: default
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/genshin
    username: genshin_user
    password: genshin_password
    hikari:
      maximum-pool-size: 100
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
logging:
  level:
    root: info
    org.springframework.cloud.stream.binding.DispatchingStreamListenerMessageHandler: error
    org.springframework.web: debug
    com.zaxxer.hikari.HikariDataSource: error
    com.zaxxer.hikari.HikariConfig: info
server:
  port: 11001