spring:
  application:
    name: genshin_manager
  profiles:
    active: deploy
    group:
      default: common
      deploy: common, deploy-db
      local: local-db, common

---
spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    url: jdbc:mariadb://localhost:3306/wuthering_waves
    username: local_user
    password: 1234

---
spring:
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        data: DEBUG

---
spring:
  config:
    activate:
      on-profile: deploy-db
  datasource:
    url: jdbc:mariadb://localhost:3306/wuthering_waves
    username: local_user
    password: 1234
